import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#f8fafc",
  },
  safeAreaContent: {
    paddingBottom: 32,
  },
  container: {
    flex: 1,
  },
  centered: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  authContainer: {
    flex: 1,
    padding: 32,
    justifyContent: "center",
    backgroundColor: "#f8fafc",
  },
  profileContainer: {
    flexGrow: 1,
    padding: 24,
    justifyContent: "center",
    backgroundColor: "#f8fafc",
  },
  title: {
    fontSize: 28,
    fontWeight: "700",
    color: "#0f172a",
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 16,
    color: "#475569",
    marginBottom: 24,
  },
  input: {
    borderWidth: 1,
    borderColor: "#e2e8f0",
    backgroundColor: "#fff",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    color: "#0f172a",
    marginBottom: 12,
  },
  textArea: {
    minHeight: 90,
    textAlignVertical: "top",
  },
  primaryButton: {
    backgroundColor: "#2563eb",
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: "center",
    marginTop: 8,
  },
  primaryButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
  },
  secondaryButton: {
    backgroundColor: "#e2e8f0",
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  eventMarker: {
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: "#2563eb",
    borderWidth: 2,
    borderColor: "#fff",
  },

  secondaryButtonText: {
    color: "#1e293b",
    fontSize: 14,
    fontWeight: "600",
  },
  logoutButton: {
    backgroundColor: "#ef4444",
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: "center",
    marginTop: 12,
  },
  logoutButtonText: {
    color: "#fff",
    fontWeight: "600",
  },
  linkButton: {
    marginTop: 16,
    alignItems: "center",
  },
  linkText: {
    color: "#2563eb",
    fontSize: 14,
    fontWeight: "600",
  },
  error: {
    color: "#dc2626",
    marginBottom: 8,
  },
  interestRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  interestInput: {
    flex: 1,
    marginBottom: 0,
  },
  tagWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 8,
  },
  tag: {
    backgroundColor: "#e0e7ff",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
  },
  tagText: {
    color: "#3730a3",
    fontWeight: "600",
  },
  profileValue: {
    fontSize: 20,
    fontWeight: "600",
    color: "#0f172a",
    marginBottom: 8,
  },
  profileBio: {
    fontSize: 16,
    color: "#475569",
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "600",
    marginBottom: 8,
    color: "#0f172a",
  },
  mutedText: {
    color: "#64748b",
  },
  timingCard: {
    backgroundColor: "#fff",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    padding: 12,
    marginBottom: 12,
  },
  timingLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: "#0f172a",
    marginBottom: 6,
  },
  timingMeta: {
    fontSize: 12,
    color: "#64748b",
  },
  timingRow: {
    flexDirection: "row",
    gap: 12,
  },
  timingField: {
    flex: 1,
  },
  timingFieldLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: "#475569",
    marginBottom: 6,
  },
  timingInput: {
    marginBottom: 0,
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  },
  searchBar: {
    position: "absolute",
    top: 52,
    left: 16,
    right: 16,
    backgroundColor: "rgba(255,255,255,0.96)",
    borderRadius: 16,
    padding: 12,
    gap: 8,
    shadowColor: "#0f172a",
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  searchRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  searchInput: {
    flex: 1,
    marginBottom: 0,
    paddingVertical: 8,
    fontSize: 14,
  },
  categoryRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 12,
  },
  categoryInput: {
    flex: 1,
    marginBottom: 0,
  },
  categoryButton: {
    borderWidth: 1,
    borderColor: "#e2e8f0",
    backgroundColor: "#fff",
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    minWidth: 110,
    alignItems: "center",
    justifyContent: "center",
  },
  categoryButtonText: {
    color: "#1e293b",
    fontSize: 12,
    fontWeight: "600",
  },
  categoryMenu: {
    marginTop: 8,
    maxHeight: 160,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 12,
    backgroundColor: "#fff",
    padding: 8,
  },
  categoryOption: {
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 8,
  },
  categoryOptionText: {
    fontSize: 14,
    color: "#0f172a",
  },
  createMapWrapper: {
    borderRadius: 16,
    overflow: "hidden",
    height: 220,
    marginBottom: 12,
  },
  createMap: {
    flex: 1,
  },
  attributionContainer: {
    position: "absolute",
    bottom: 12,
    left: 12,
    backgroundColor: "rgba(255,255,255,0.8)",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  attributionText: {
    fontSize: 12,
    color: "#1e293b",
  },
  profileButton: {
    position: "absolute",
    top: 140,
    right: 16,
    backgroundColor: "rgba(15, 23, 42, 0.8)",
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
  },
  profileButtonText: {
    color: "#fff",
    fontWeight: "600",
  },
  createEventButton: {
    position: "absolute",
    top: 140,
    left: 16,
    backgroundColor: "rgba(37, 99, 235, 0.9)",
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
  },
  createEventButtonText: {
    color: "#fff",
    fontWeight: "600",
  },
  demoAreaButton: {
    position: "absolute",
    top: 188,
    left: 16,
    backgroundColor: "rgba(15, 23, 42, 0.75)",
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
  },
  demoAreaButtonText: {
    color: "#fff",
    fontWeight: "600",
  },
  bottomSheet: {
    position: "absolute",
    left: 16,
    right: 16,
    bottom: 24,
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 16,
    shadowColor: "#0f172a",
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 6,
  },
  bottomSheetTitle: {
    fontSize: 18,
    fontWeight: "700",
    marginBottom: 8,
    color: "#0f172a",
  },
  bottomSheetText: {
    fontSize: 14,
    color: "#475569",
    marginBottom: 12,
  },
  bottomSheetMeta: {
    fontSize: 12,
    color: "#94a3b8",
    marginBottom: 12,
  },
  chatContainer: {
    flex: 1,
    backgroundColor: "#f8fafc",
    padding: 16,
  },
  chatHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  chatTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#0f172a",
  },
  chatMessages: {
    paddingBottom: 16,
  },
  chatMessage: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 12,
    marginBottom: 12,
    shadowColor: "#0f172a",
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 1,
  },
  chatDisplayName: {
    fontSize: 12,
    fontWeight: "600",
    color: "#475569",
    marginBottom: 4,
  },
  chatText: {
    fontSize: 14,
    color: "#0f172a",
  },
  chatInputRow: {
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
  },
  chatInput: {
    flex: 1,
    marginBottom: 0,
  },
  adminPanel: {
    marginTop: 8,
    marginBottom: 12,
    gap: 8,
  },
  requestRow: {
    backgroundColor: "#f8fafc",
    borderRadius: 12,
    padding: 12,
    gap: 8,
  },
  requestInfo: {
    gap: 4,
  },
  requestText: {
    fontSize: 12,
    color: "#0f172a",
    fontWeight: "600",
  },
  requestStatus: {
    fontSize: 12,
    color: "#64748b",
  },
  requestActions: {
    flexDirection: "row",
    gap: 8,
  },
  rejectButton: {
    backgroundColor: "#fee2e2",
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  rejectButtonText: {
    color: "#b91c1c",
    fontSize: 14,
    fontWeight: "600",
  },
  loadingEventsBadge: {
    position: "absolute",
    top: 110,
    alignSelf: "center",
    backgroundColor: "rgba(15, 23, 42, 0.8)",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
  },
  loadingEventsText: {
    color: "#fff",
    fontSize: 12,
  },
  privacyRow: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 12,
  },
  privacyToggle: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#cbd5f5",
    borderRadius: 12,
    paddingVertical: 10,
    alignItems: "center",
  },
  privacyToggleActive: {
    backgroundColor: "#e0e7ff",
    borderColor: "#6366f1",
  },
  privacyToggleText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#475569",
  },
  privacyToggleTextActive: {
    color: "#3730a3",
  },
});
